[tool.flwr.app]
publisher = "my-username"
name = "my-awesome-app"
version = "1.0.0"

[tool.flwr.app.components]
serverapp = "my_awesome_app.server:app"
clientapp = "my_awesome_app.client:app"

[tool.flwr.app.config]
num-server-rounds = 5
fraction-fit = 1.0
fraction-evaluate = 1.0
local-epochs = 1

[tool.flwr.federated-simulation]
num-partitions = 2